import { Prompt } from "next/font/google";
import "./globals.css";
import SessionProvider from "../components/SessionProvider";

import { Toaster } from "@/components/ui/toaster";

const prompt = Prompt({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

export const metadata = {
  title: "UNITED 1999 PLUS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={prompt.className}>
        <SessionProvider>{children}</SessionProvider>
        <Toaster />
      </body>
    </html>
  );
}
